services:
  - type: web
    name: effekt-music-bot
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt

    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: STORAGE_DIR
        value: /data/files
